site_name: Alochol Adsorption by Nacl Walls 
site_url: https://physicistrealm.github.io/alcoholbetweennaclwalls/

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.instant
    - toc.integrate
    - content.code.copy

nav:
  - Home: index.md
  - Tutorials:
      - Free Sampling: free_sampling.md
      - Umbrella Sampling: umbrella_sampling.md
  - References: references.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.superfences

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css


